#index:
#    path: /
#    controller: App\Controller\DefaultController::index



demarrage:
    path: /
    controller: App\Controller\ArticleController::demarrage

index:
    path: /accueil
    controller: App\Controller\HomeController::accueil


apropos:
    path: /apropos
#   controller: App\Controller\HomeController::apropos


contacter:
    path: /contacter
    controller: App\Controller\HomeController::contacter




